### ISSUE TITLE
Email styles are missing

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-theme-blank-sass#84] opened 2016-07-14 14:02 UTC
For now we don't have `email.css`, `email-linline.css` and `email-fonts.css`
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/templates/template-email.html#non-inline-styles

**Comment by Igloczek** [comment] 2016-07-15 08:47
Looks like we have another problem - M2 is not looking into `pub` folder for email styles... It search for `less` and `css` files in`vendor` only.

**Comment by elineopsommer** [comment] 2016-10-10 14:11
Any updates on this?

**Comment by Igloczek** [comment] 2016-10-10 14:24
Unfortunately any update I can provide is "lack of time" 😢

**Comment by elineopsommer** [comment] 2016-10-10 14:29
@Igloczek Is there any workaround for this?

**Comment by Januszpl** [comment] 2016-10-10 14:35
@elineopsommer you can create `web/css/email/email.scss` and then after styles compilation copy from `pub/..../css/email/email.css` to`yourtheme/web/css/email.css`

However there can be issue with importing external fonts and I need to check again M2 core email solution as they have originally a few more less files for emails.

**Comment by refaelgold** [comment] 2017-01-11 18:24
any updates with this issue?

**Comment by Igloczek** [comment] 2017-01-12 16:17
Nope, lack of time. For now we stick with LESS just for emails.

**Comment by Januszpl** [comment] 2017-08-25 18:35
I've start working on this matter. So in first weeks of next month I should sent some pull request.

**Comment by VegtMedia-Alex** [comment] 2018-07-16 09:18
Any updates?

**Comment by erfanimani** [comment] 2018-07-16 10:26
> @Igloczek Looks like we have another problem - M2 is not looking into pub folder for email styles... It search for less and css files in vendor only.

Is this still the case for M2.1+?

**Comment by Igloczek** [comment] 2018-07-20 09:44
@Januszpl was working on it, I don't know what's the status now.

**Comment by erfanimani** [comment] 2018-07-21 06:34
Ah ok, no problem.

Just FYI, I think it really does look into pub folder for email styles, unless I'm misunderstanding something.

Also see `\Magento\Email\Model\Template\Filter::getCssFilesContent`.

**Comment by Januszpl** [comment] 2018-07-30 21:02
@alexvandervegt - does it stop you for having styles in emails? (still can use .less files for emails)

There had been some issues with resolving conflicts before but they are fixed now. 

Now there is still issue with
@charset "UTF-8";
that appears on top of the email-inline.css file (after compilation) as we have  non standard ASCII characters in our email code and sass when detecting such a characters and this line.

Normally it's fine but in emogrifier cause error - M is using this module to transform css rules from email-inline.css to put into email html tags. In current unreleased version of emogrifier the error display is fixed, but it still doesnt suppport it, just ingore the value.

Magento in some version updated this lib to 2.0.0 - but it fixed only some other issue - not this one.

The problem is with:
However sass add UTF-8 Charset to the top of file because of file`lib/web/css/source/lib/variables/_typography.less` and line 223
`@blockquote__content-before: '\2014 \00A0';`

which is used in mixin `@mixin lib-typography-blockquote` here `theme-blank-sass/styles/vendor/magento-ui/_typography.scss`

which is used here `magento2/sassblank/vendor/magento/magento2-base/lib/web/css/source/lib/_typography.less`

which is used originally in Blank theme here `vendor/magento/theme-frontend-blank/web/css/source/_email-base.less` and in our implementation here `theme-blank-sass/styles/email/_email-base-inline.scss`

@Igloczek 
### our solutions
1. Implement to frontools my initial fix for this https://github.com/SnowdogApps/magento2-frontools/pull/247
2. Wait for new release of emogrifier (and wait for Magento update or use "X.Y.Z as 2.0.0" alias in composer in projects
3. Override this line that cause errors and replace it with sth else

**Comment by VegtMedia-Alex** [comment] 2018-08-02 09:07
Hi @Januszpl I implemented this PullRequest: https://github.com/SnowdogApps/magento2-theme-blank-sass/pull/153 and everything is working now.

**Closed as completed** 2019-07-08 18:19 UTC
Labels: bug
